name: conda-release

on:
  push:
    branches:
    - master
    - conda-release
    tags:
    - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up miniconda with python 3.8
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.8
        activate-environment: test
        environment-file: .github/environment.yml
        auto-activate-base: false
    - name: Install build tools
      shell: bash -l {0}
      run: |
        conda install conda-build anaconda-client conda-verify
    - name: Build conda package
      shell: bash -l {0}
      run: |
        conda build .
    - name: Upload to haasad conda channel
      if: startsWith(github.ref, 'refs/tags/v')
      shell: bash -l {0}
      run: |
        anaconda -t ${{ secrets.CONDA_TOKEN }} upload /usr/share/miniconda/envs/test/conda-bld/noarch/*.tar.bz2
